### ISSUE TITLE
[Bug report] In the early morning, ES migration data multiple ES nodes stuck on CFS for about 5 minutes

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#863] opened 2020-08-31 04:03 UTC
**Describe the bug**
In the early morning, ES migration data multiple ES nodes stuck on CFS for about 5 minutes，I checked：

* [X] Network traffic
* [x] DN load

**Environment**

```
cfs-client -v
ChubaoFS Client
Version : v2.1.0
Branch  : master
Commit  : 1c7f69a77f8d136a5c1c4d71e47156dcea44b403
Build   : go1.12.6 linux amd64 2020-08-12 14:12

cfs-server -v
ChubaoFS Server
Version : v2.1.0
Branch  : master
Commit  : 820b4b58094baa49d9cf0ba9507d5656424dc8aa
Build   : go1.12.6 linux amd64 2020-08-28 07:29

```

**To Reproduce**

In the early morning, a large amount of data was migrated from the SSD ES node to the CFS ES node of the SATA disk，About 5-6 nodes out of more than 100 ES nodes will get stuck

**Expected behavior**

The local disk ES does not have this problem. CFS did not appear before, it seems to appear after updating the DN version and turning on automatic repair

**Additional context**
[client_warn.log](https://gist.github.com/zcola/7954b073dd0970faa65c6fc6317cf28e)

**Comment by zcola** [comment] 2020-09-01 02:08
After closing all DN AutoRepair, it did not appear again last night

**Comment by yinlei-jinan** [comment] 2020-09-09 02:05
caused by write error, fixed by https://github.com/chubaofs/chubaofs/pull/867

**Comment by shuoranliu** [comment] 2020-10-13 04:27
I'm going to close this issue based on the comments before. @zcola please feel free to re-open it if you find it still happens.

**Closed by shuoranliu** 2020-10-13 04:27 UTC
Labels: bug
